server:
  port: 8888

spring:
  application:
    name: microservicio-config-server
  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
