server:
  port: ${msvc-eureka-port}

spring:
  application:
    name: microservicio-eureka

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    server-url:
      defaultZone: http://localhost:${server.port}/eureka/