spring:
  application:
    name: microservicio-gateway
  config:
    import: optional:configserver:http://localhost:8888

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${secret-id}
            client-secret: ${secret-client}
            scope:
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

