INSERT INTO cliente (nombre, apellidoP, apellidoM, email) VALUES('Juan', 'Pérez', 'Gómez', 'juan.perez@example.com');
INSERT INTO cliente (nombre, apellidoP, apellidoM, email) VALUES('María', 'López', 'Ramírez', 'maria.lopez@example.com');
INSERT INTO cliente (nombre, apellidoP, apellidoM, email) VALUES('Carlos', 'Hernández', 'Martínez', 'carlos.hernandez@example.com');
INSERT INTO cliente (nombre, apellidoP, apellidoM, email) VALUES('Ana', 'García', 'Ruiz', 'ana.garcia@example.com');
INSERT INTO cliente (nombre, apellidoP, apellidoM, email) VALUES('Luis', 'Sánchez', 'Torres', 'luis.sanchez@example.com');
INSERT INTO cliente (nombre, apellidoP, apellidoM, email) VALUES('Laura', 'Díaz', 'Flores', 'laura.diaz@example.com');
INSERT INTO cliente (nombre, apellidoP, apellidoM, email) VALUES('Jorge', 'Ramírez', 'Morales', 'jorge.ramirez@example.com');
INSERT INTO cliente (nombre, apellidoP, apellidoM, email) VALUES('Lucía', 'Mendoza', 'Núñez', 'lucia.mendoza@example.com');
INSERT INTO cliente (nombre, apellidoP, apellidoM, email) VALUES('Pedro', 'Ortega', 'Silva', 'pedro.ortega@example.com');
INSERT INTO cliente (nombre, apellidoP, apellidoM, email) VALUES('Elena', 'Cruz', 'Fernández', 'elena.cruz@example.com');
INSERT INTO cliente (nombre, apellidoP, apellidoM, email) VALUES('Axel Daniel', 'Bartolo', 'Maya', 'axeldanuel@example.com');
